[project]
name = "correct-hooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Phillip Diffley", email = "7283778+pdiffley@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cryptography>=50.0.2",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
]

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
